sudo: required

language: python

python:
    - 2.7
    - 3.5

services:
    - docker

before_install:
    - docker build -t foobar .
    - docker run --name foobar -d -p 5000:80 -it -v /var/log/foobar:/var/log/foobar foobar

# command to install dependencies
install: 
    - pip install -r requirements.txt

# command to run tests
script: 
    - pytest tests
    - pytest tests/system/app.py
